sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 1
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    hci_interface: 0
    batt_entities: False
    encryptors:
               '9C:F6:DD:33:D2:A4': '17d17f5fc45ead44e254f929'
    report_unknown: False
    whitelist: False